export let THEME_LIGHT = {
    NAME: 'LIGHT',
    LOGO_URL: 'https://assets.ccbp.in/frontend/react-js/nxt-watch-logo-light-theme-img.png',
    THEME_TOGGLER: "https://img.icons8.com/glyph-neue/256/bright-moon.png",
    PROFILE_LOGO: "https://assets.ccbp.in/frontend/react-js/nxt-watch-profile-img.png ",
    BACKGROUND_COLOR: ' #ffffff',
    PAGE_BACKGROUND_COLOR: '#eeee',
    PAGE_BANNER_BG_COLOR: '  #dfdfdf',
    LABEL: '#909090',
    INPUT: '#0f0f0f',
    LOGIN_BTN_BG_COLOR: '#3b82f6',
    LOGIN_BTN_TXT_COLOR: ' #f8fafc',
    SHOW_PASSWORD: 'black',
    LOGOUT_BTN_BORDER_COLOR: '#3b82f6',
    LOGOUT_BTN_TXT_COLOR: '#3b82f6',
    SEARCH_BAR_BACKGROUND: '#ffffff',
    SEARCH_BAR_BORDER_COLOR: '#929292',
    DASH_BOARD_TXT_COLOR: '#606060',
    DASH_BOARD_COLOR: '#ffffff',
    SUBSCRIBER_COUNT_TXT_SIZE: 'smaller',
    DESCRIPTION_FONT_SIZE: 'medium',
    RETRY_BACKGROUND_BUTTON: ' #4f46e5',
    RETRY_BUTTON_COLOR: '#ffffff'
  }
  
  export let THEME_DARK = {
    NAME: 'DARK',
    LOGO_URL: 'https://assets.ccbp.in/frontend/react-js/nxt-watch-logo-dark-theme-img.png',
    THEME_TOGGLER: "https://img.icons8.com/ios11/600/FFFFFF/sun.png",
    BACKGROUND_COLOR: ' #231f20',
    PAGE_BACKGROUND_COLOR: '#0f0f0f',
    PAGE_BANNER_BG_COLOR: ' #212121',
    LABEL: '#f8fafc',
    INPUT: '#ffffff',
    SHOW_PASSWORD: '#f8fafc',
    PROFILE_LOGO: "https://assets.ccbp.in/frontend/react-js/nxt-watch-profile-img.png ",
    LOGIN_BTN_BG_COLOR: '#3b82f6',
    LOGIN_BTN_TXT_COLOR: ' #f8fafc',
    LOGOUT_BTN_BORDER_COLOR: '#ffffff',
    LOGOUT_BTN_TXT_COLOR: '#ffffff',
    SEARCH_BAR_BORDER_COLOR: '#adadad',
    SEARCH_BAR_BACKGROUND: '#0f0f0f',
    DASH_BOARD_TXT_COLOR: '#ffffff',
    DASH_BOARD_COLOR: '#231f20',
    SUBSCRIBER_COUNT_TXT_SIZE: 'smaller',
    DESCRIPTION_FONT_SIZE: 'medium',
    RETRY_BACKGROUND_BUTTON: ' #4f46e5',
    RETRY_BUTTON_COLOR: '#ffffff'
  
  }